stages:
  data_prep:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - params.yaml
    params:
      - data.raw_path
      - data.processed_path
      - data.random_state
    outs:
      - data/processed/cleaned_accidents.csv

  register_model:
    cmd: python src/register_model.py
    deps:
      - src/register_model.py
      - params.yaml
    params:
      - registry.promotion_metric
      - registry.promotion_threshold
